name: Compile code
on:
  release:
    types:
      - created

jobs:
  build:
    name: Compile Code
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Compile code into MSI package
        run: python compile.py bdist_msi

      - name: Move Files
        run: |
          FILE_NAME="TroveFileExtractor"
          RELEASE_NAME="${{ github.event.release.tag_name }}"
          NEW_FILE_NAME="${FILE_NAME}_${RELEASE_NAME}-win64.msi"
          move dist/TroveFileExtractor.msi $NEW_FILE_NAME

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "TroveFileExtractor_${{ github.event.release.tag_name }}-win64.msi"
          token: ${{ secrets.COMPILER }}