name: Compile EXE
on:
    push:
      tags:
        - "v*.*"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install required modules
        run: python -m pip install -r requirements.txt

      - name: Compile code into EXE
        run: python compile.py bdist_msi

      - name: Move Files
        run: move dist/*.exe "TroveFileExtractor.exe"

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "TroveFileExtractor.exe"
          token: ${{ secrets.COMPILER }}