name: Compile code
on:
  release:
    types:
      - created

jobs:
  build:
    name: Compile Code
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Compile code into MSI package
        run: python compile.py bdist_msi

      - name: Move Files
        run: |
          $env:FILE_NAME="TroveFileExtractor"
          $env:RELEASE_NAME="${{ github.event.release.name }}"
          $env:NEW_FILE_NAME="${env:FILE_NAME}_${env:RELEASE_NAME}-win64.msi"
          Move-Item "dist/TroveFileExtractor.msi" ".\TroveFileExtractor.msi"
          Rename-Item ".\TroveFileExtractor.msi" "${env:NEW_FILE_NAME}"

      - name: Upload file to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "TroveFileExtractor_${{ github.event.release.name }}-win64.msi"
          asset_name: "TroveFileExtractor_${{ github.event.release.name }}-win64.msi"
          asset_content_type: application/x-msi